### ISSUE TITLE
Possible CDP error - CDP-8C52

### ISSUE THREAD

**Issue by BSBMteam** [chise/ids#1]
This entry:
`CDP-8C52	&CDP-8C52;	𠃌口`
could be written as:
`CDP-8C52	&CDP-8C52;	⿹𠃌口`

Also: 𠔼
`CDP-894A	&I-CDP-894A;	⿴冂一` ↓
`CDP-894A	&I-CDP-894A;	⿵冂一`

http://www.chise.org/est/view/character/%F0%A0%94%BC

**Comment by chise** [comment]
Thanks for your report.  I fixed them:
https://gitlab.chise.org/CHISE/ids/commit/d6ebc13d8db41e6451823c4059151d4d4aad362b
