### ISSUE TITLE
Is it appropriate to describe 鬯 as composition of 𠂭凵匕?

### ISSUE THREAD

**Issue by wmjordan** [chise/ids#11]
as title.

**Comment by Yukinoroh** [comment]
In the database that decomposition is represented by two entries:
U+9B2F	鬯	⿱𠚍匕
 and
U-0002068D	𠚍	⿶凵𠂭

By substituting 𠚍 with ⿶凵𠂭, you get ⿱⿶凵𠂭匕.
That is done by the software using the database.

**Comment by wmjordan** [comment]
Thank you for taking time to explain.
Somehow I messed up the database on my computer with a very old copy.
I checked the recent database and saw the result your pointed out.
Sorry for the trouble I caused..
