### ISSUE TITLE
Functional structure of 𤤘 must be ⿱丠土, not ⿱北王

### ISSUE THREAD

**Issue by kanou-h** [chise/ids#17]
𤤘 (U-00024918 in IDS-UCS-Ext-B-3.txt, M-05084 in IDS-Daikanwa-03.txt) is defined as
“⿱北王” as it is arranged at the position of radical 玉 plus 4 strokes in CJK Ideographs Ext B,
but it is based on the apparent structure (Daikanwa Jiten classifies it into radical 土). 

In Shuowen Jiezi (at 卷八上) , 𤤘 is included in the description of 丠 being noted as “古文从土”.
Therefore the functional structure must be “⿱丠土”.

**Comment by chise** [comment]
Thanks for your report.  I fixed it.

https://github.com/chise/ids/commit/f0d79f96306cd8596510f7eb4944c87c88df4c21
https://github.com/chise/ids/commit/f6e00d13130276cb5586c656e18bf18c5d07faa8
